<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>doctest</string>
		<string>rdoctest</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~R</string>
	<key>name</key>
	<string>DocTest</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.html.markdown</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.rdoc.test</string>
	<key>uuid</key>
	<string>B6DE5244-41D3-4F37-B1C7-B0A76538FB0B</string>
</dict>
</plist>
