<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dryml</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\s*(&lt;[^!?%/](?!.+?(/&gt;|&lt;/.+?&gt;))|&lt;[!%]--(?!.+?--%?&gt;)|&lt;%[!]?(?!.+?%&gt;))</string>
	<key>foldingStopMarker</key>
	<string>^\s*(&lt;/[^&gt;]+&gt;|[/%]&gt;|--&gt;)\s*$</string>
	<key>keyEquivalent</key>
	<string>^~R</string>
	<key>name</key>
	<string>DRYML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.xml</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.ruby.dryml</string>
	<key>uuid</key>
	<string>04CFCBEE-D8C9-48E5-BA12-6E5D1E519CE7</string>
</dict>
</plist>
